name: Build and Release

on:
  # workflow_dispatch:
  push:
    branches:
      - master

env:
  EXECUTABLE_NAME: file-net.exe
  BUILD_MODE: release

jobs:
  Cargo-build--Js-upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build ${{ env.BUILD_MODE }}
        run: cargo build --${{ env.BUILD_MODE }}
      - name: move executable
        run: |
          mkdir ./.releases
          cp ./target/$BUILD_MODE/$EXECUTABLE_NAME ./.releases/
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          path: ./.releases/${{ env.EXECUTABLE_NAME }}
          name: ${{ env.EXECUTABLE_NAME }}
     
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest
      - name: Make Release with js
        uses: actions/github-script@main
        with: 
          script: |
            const main = require('.github/workflows/create-git-release.js')
            await main({github, context, core})
        